xpack.security.enabled: ${XPACK_SECURITY_ENABLED}
node.name: ${NODE_NAME}
cluster.name: ${CLUSTER_NAME}
discovery.seed_hosts: ${DISCOVERY_SEED_HOSTS}
cluster.initial_master_nodes: ${CLUSTER_INITIAL_MASTER_NODES}
bootstrap.memory_lock: ${BOOTSTRAP_MEMORY_LOCK}
network.host: ${NETWORK_HOST}
http.port: ${HTTP_PORT}
#xpack.security.enabled: true
xpack.security.http.ssl.enabled: ${XPACK_SECURITY_HTTP_SSL_ENABLED}
xpack.security.http.ssl.key: ${XPACK_SECURITY_HTTP_SSL_KEY}
xpack.security.http.ssl.certificate: ${XPACK_SECURITY_HTTP_SSL_CERTIFICATE}
xpack.security.http.ssl.certificate_authorities: ${XPACK_SECURITY_HTTP_SSL_CERTIFICATE_AUTHORITIES}
xpack.security.http.ssl.verification_mode: ${XPACK_SECURITY_HTTP_SSL_MODE}
xpack.security.transport.ssl.enabled: ${XPACK_SECURITY_TRANSPORT_SSL_ENABLED}
xpack.security.transport.ssl.key: ${XPACK_SECURITY_TRANSPORT_SSL_KEY}
xpack.security.transport.ssl.certificate: ${XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE}
xpack.security.transport.ssl.certificate_authorities: ${XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE_AUTHORITIES}
xpack.security.transport.ssl.verification_mode: ${XPACK_SECURITY_TRANSPORT_SSL_MODE}                
xpack.license.self_generated.type: ${XPACK_LICENCE_SELF_GENERATED_TYPE}






