---

nodes_list: [master, node1]
xpack: enable
certregen: no
monitoring: enable
garphana_pass: admin

image_elastic: test1
tag_elastic: latest

image_kibana: kibana
tag_kibana: latest


image_logstash: logstash
tag_logstash: latest

elastic_version: 7.17.1
elastic_password: "Test@1234"

kibana_version: 7.17.1
kibana_password: "Test@1234"








