version: '3.7'
services:


  master:
    image: test1:latest
    container_name: master
    environment:
      - XPACK_SECURITY_ENABLED=true
      - NODE_NAME=master
      - CLUSTER_NAME=es-docker-cluster
      - DISCOVERY_SEED_HOSTS=node1
      - CLUSTER_INITIAL_MASTER_NODES=master,node1
      - BOOTSTRAP_MEMORY_LOCK=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - NETWORK_HOST=0.0.0.0
      - HTTP_PORT=9200
      - XPACK_SECURITY_HTTP_SSL_ENABLED=true
      - XPACK_SECURITY_HTTP_SSL_KEY=/usr/share/elasticsearch/config/certificates/master/master.key
      - XPACK_SECURITY_HTTP_SSL_CERTIFICATE=/usr/share/elasticsearch/config/certificates/master/master.crt
      - XPACK_SECURITY_HTTP_SSL_CERTIFICATE_AUTHORITIES=/usr/share/elasticsearch/config/certificates/ca/ca.crt
      - XPACK_SECURITY_HTTP_SSL_MODE=certificate
      - XPACK_SECURITY_TRANSPORT_SSL_ENABLED=true
      - XPACK_SECURITY_TRANSPORT_SSL_KEY=/usr/share/elasticsearch/config/certificates/master/master.key
      - XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE=/usr/share/elasticsearch/config/certificates/master/master.crt
      - XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE_AUTHORITIES=/usr/share/elasticsearch/config/certificates/ca/ca.crt
      - XPACK_SECURITY_TRANSPORT_SSL_MODE=certificate                
      - XPACK_LICENCE_SELF_GENERATED_TYPE=trial

 
     
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      #- ./:/usr/share/elasticsearch/config/certs
      - ./certs:/usr/share/elasticsearch/config/certificates
      - ./data:/data




    ports:
      - 9200:9200
      - 9300:9300
   
  node1:
    image: test1:latest
    container_name: node1
    environment:
      - XPACK_SECURITY_ENABLED=true
      - NODE_NAME=node1
      - CLUSTER_NAME=es-docker-cluster
      - DISCOVERY_SEED_HOSTS=node1
      - CLUSTER_INITIAL_MASTER_NODES=master,node1
      - BOOTSTRAP_MEMORY_LOCK=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - NETWORK_HOST=0.0.0.0
      - HTTP_PORT=9200
      - XPACK_SECURITY_HTTP_SSL_ENABLED=true
      - XPACK_SECURITY_HTTP_SSL_KEY=/usr/share/elasticsearch/config/certificates/node1/node1.key
      - XPACK_SECURITY_HTTP_SSL_CERTIFICATE=/usr/share/elasticsearch/config/certificates/node1/node1.crt
      - XPACK_SECURITY_HTTP_SSL_CERTIFICATE_AUTHORITIES=/usr/share/elasticsearch/config/certificates/ca/ca.crt
      - XPACK_SECURITY_HTTP_SSL_MODE=certificate
      - XPACK_SECURITY_TRANSPORT_SSL_ENABLED=true
      - XPACK_SECURITY_TRANSPORT_SSL_KEY=/usr/share/elasticsearch/config/certificates/node1/node1.key
      - XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE=/usr/share/elasticsearch/config/certificates/node1/node1.crt
      - XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE_AUTHORITIES=/usr/share/elasticsearch/config/certificates/ca/ca.crt
      - XPACK_SECURITY_TRANSPORT_SSL_MODE=certificate                
      - XPACK_LICENCE_SELF_GENERATED_TYPE=trial

 
     
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      #- ./:/usr/share/elasticsearch/config/certs
      - ./certs:/usr/share/elasticsearch/config/certificates
      - ./data:/data











  kibana:
    image: kibana:latest
    command: >
     bash -c '
       bash password.sh Test@1234 Test@1234
       ls -altr
       pwd
       cat passwords.txt
     '
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./certs:/usr/share/kibana/certs
    ports:
      - 5601:5601



  logstash:
    image: logstash:latest
    volumes:
      - ./logstash/logstash.yml:/usr/share/kibana/logstash/logstash.yml
      - ./certs:/usr/share/logstash/certs
    #ports:
    #  - 5601:5601





  eexporter:
    container_name: eexporter
    image: justwatch/elasticsearch_exporter:1.0.2
    command:
        - '-es.uri=https://elastic:Test@1234@master:9200'
        - '-es.ca=/certs/ca/ca.crt'
    restart: always
    volumes:
      - ./certs:/certs
    ports:
        - "9108:9108"


  prometheus:
    image: prom/prometheus:0.18.0
    container_name: prometheus
    volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'

  grafana:
    image: grafana/grafana:6.1.6
    container_name: grafana
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
        - prometheus
    ports:
        - "3000:3000" 


       